---
title: "Homework 4"
author: "Laura Brubaker-Wittman"
date: "10/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1:

Write a simple R function, Z.prop.test(), that can perform one- or two-sample Z-tests for proportion data, using
the following guidelines:

* Your function should take the following arguments: **p1** and **n1** (no default) representing the estimated
proportion and sample size (i.e., based on your sample data); **p2** and **n2** (both defaulting to NULL) that
contain a second sample’s proportion and sample size data in the event of a two-sample test; **p0** (no default)
as the expected value for the population proportion; and alternative (default “two.sided”) and **conf.level**
(default   0.95), to be used in the same way as in the function t.test().

* When conducting a two-sample test, it should be **p1** that is tested as being smaller or larger than **p2**
when alternative=“less” or alternative=“greater”, the same as in the use of x and y in the function t.test().

* The function should perform a one-sample Z-test using **p1**, **n1**, and **p0** if either p2 or n2 (or both) is
NULL.

* The function should contain a check for the rules of thumb we have talked about (*n* ∗ *p* > 5 and *n*  ∗
(1−**p) > 5) to ensure the validity of assuming the normal distribution in both the one- and two-sample settings.
If this is violated, the function should still complete but it should also print an appropriate warning message.

* The function should return a list containing the members **Z** (the test statistic), **P** (the appropriate p
value),and CI (the two-sided CI with respect to “conf.level” around **p1** in the case of a one-sample test and
around **p2-p1** in the case of a two-sample test). For all test alternatives (“two.sided”, “greater”, “less”),
calculate symmetric CIs based on quantiles of the normal distribution rather than worrying about calculating
single-limit confidence bounds.

Ok, so I worked on this for awhile and really got nowhere. I just did not have the time to figure it out. I
started by looking at what the t.test function involves, based on the Help menu:

    t.test(x, ...)

    ## Default S3 method:
    t.test(x, y = NULL,
       alternative = c("two.sided", "less", "greater"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95, ...)

    ## S3 method for class 'formula'
    t.test(formula, data, subset, na.action, ...)
    
I also looked up some resources on z-tests and scores, and while I get the concept, I am still feeling not 
confident at writing equations. I am going to go on with this homework and if I have time to come back I will. 
Hopefully my peer commentators will have some thoughts on this as well!


